// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TeaAPI.Model;

namespace TeaAPI.Migrations
{
    [DbContext(typeof(TeaContext))]
    partial class TeaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TeaAPI.Model.Goods", b =>
                {
                    b.Property<int>("GId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("GName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GNum")
                        .HasColumnType("int");

                    b.Property<float>("GPrice")
                        .HasColumnType("real");

                    b.Property<string>("GRemark")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GState")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GType")
                        .HasColumnType("int");

                    b.Property<string>("GoodsPicture")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GId");

                    b.ToTable("Goods");
                });

            modelBuilder.Entity("TeaAPI.Model.GoodsType", b =>
                {
                    b.Property<int>("GTId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("GTName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GTId");

                    b.ToTable("GoodsType");
                });

            modelBuilder.Entity("TeaAPI.Model.Menu", b =>
                {
                    b.Property<int>("Mid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("MUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Mid");

                    b.ToTable("Menu");
                });

            modelBuilder.Entity("TeaAPI.Model.OrderInfo", b =>
                {
                    b.Property<int>("OIId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("GNos")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GNum")
                        .HasColumnType("int");

                    b.Property<string>("Gremark")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OINode")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("OIId");

                    b.ToTable("OrderInfo");
                });

            modelBuilder.Entity("TeaAPI.Model.Orders", b =>
                {
                    b.Property<int>("OId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("OName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ONo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OPhone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OStartTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Oaddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OendTime")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Omoney")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Ostate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UIds")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("OId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("TeaAPI.Model.ShoppingTrolley", b =>
                {
                    b.Property<int>("SIId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("GNos")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GTNum")
                        .HasColumnType("int");

                    b.Property<string>("UNos")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SIId");

                    b.ToTable("ShoppingTrolley");
                });

            modelBuilder.Entity("TeaAPI.Model.Users", b =>
                {
                    b.Property<int>("UId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ConsigneeAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConsigneeName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConsigneePhone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UPass")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("URealName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Ubirthday")
                        .HasColumnType("datetime2");

                    b.HasKey("UId");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
